backend:
  name: github
  repo: ВАШ_GITHUB_USERNAME/ВАШ_РЕПОЗИТОРИЙ # Название вашего репозитория
  branch: main # Или master
  base_url: https://gagarin-decap-oauth.polinom11.workers.dev # URL вашего Worker
  auth_endpoint: /auth

media_folder: "images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Записи блога"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Анонс", name: "description", widget: "text" }
      - { label: "Текст статьи", name: "body", widget: "markdown" }
