backend:
  name: github
  repo: polinom11/polinom11.github.io # Укажите ваш GitHub-аккаунт и имя репозитория
  branch: main # Основная ветка (main или master)
  base_url: https://sveltia-cms-auth.vercel.app
  auth_endpoint: /auth

# Папка для загружаемых медиафайлов
media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Статьи и Блог"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Анонс", name: "description", widget: "text" }
      - { label: "Главное изображение", name: "image", widget: "image", required: false }
      - { label: "Текст статьи", name: "body", widget: "markdown" }
